[project]
name = "mcp_client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.39.9",
    "mcp==1.12.2",
    "strands-agents-tools>=0.2.1",
]
