[project]
name = "mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp==1.11.0",
    "openai>=1.97.1",
]

[dependency-groups]
dev = [
    "bedrock-agentcore-starter-toolkit>=0.1.0",
    "boto3>=1.39.9",
]
